services:
    mysql:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    app:
        build:
            context: .
            dockerfile: Dockerfile
            # target: base # Solo si tienes multistage builds
        container_name: laravel-app-dev
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - laravel_network
        command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
    mysql_data:

networks:
    laravel_network:
